# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: grepp google sheet proxy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn build

        env:
          REACT_APP_GOOGLE_DOC_ID: ${{ secrets.REACT_APP_GOOGLE_DOC_ID }}
          REACT_APP_GOOGLE_SHEET_ID: ${{ secrets.REACT_APP_GOOGLE_SHEET_ID }}
          REACT_APP_GOOGLE_SHEET_NAME: ${{ secrets.REACT_APP_GOOGLE_SHEET_NAME }}

          REACT_APP_GOOGLE_SERVICE_CLIENT_EMAIL: ${{ secrets.REACT_APP_GOOGLE_SERVICE_CLIENT_EMAIL }}
          REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY: ${{ secrets.REACT_APP_GOOGLE_SERVICE_PRIVATE_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
